easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'image', template: 'list_partners.html.twig' }

        Image:
            class: App\Entity\Image
            form:
                fields:
                    - { property: 'filename', type: 'vich_file' }
        Belcode: App\Entity\Belcode